version: "1"

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosimple
    - ineffassign
    - unused
    - typecheck

issues:
  # Напрямую в issues, без лишних вложений
  exclude-dirs:
    - mocks
    - internal/mocks
    - test/mocks

  exclude-rules:
    # Игнорируем все проверки в моках
    - path: (.*_mock\.go|mocks/.*|internal/mocks/.*|test/mocks/.*)
      linters:
        - all
    
    # В тестах отключаем лишнее
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam # исправил опечатку