# .golangci.yml
run:
  timeout: 5m
  skip-dirs:
    - internal/clients/telegram/mocks
    - internal/clients/llm/mocks

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck

issues:
  exclude:
    - ".*_m\\.Called undefined"
    - "mock\\.AssertExpectations undefined"
    - "typecheck"