name: CI/CD Pipeline

on: 
  push:
    branches: ["main", "feature*"]
    tags: ['v*']
  pull_request:
    branches: ["main", "feature*"]
env:
  GO_VERSION: '1.23.2'
  ALPINE_VERSION: '3.20'
  PORT: '80'
  LINTER_VERS: 'v2.0.2'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkoute code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup_go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ env.LINTER_VERS }}
          args: --timeout=5m

  go_test:
    name: Tests 
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkoute code
        uses: actions/checkout@v4
    
      - name: Setup Go
        uses: actions/setup_go@v5
        with: 
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Download dependencies
        uses: go mod Download

      - name: Run tests with coverage
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
          go tool cover -func=coverage.txt
          