name: CI/CD Pipeline

on: 
  push:
    branches: ["main", "feature*"]
    tags: ['v*']
  pull_request:
    branches: ["main", "feature*"]
    
jobs:
  ci:
    uses: Mark-Grigorev/central-ci-cd/.github/workflows/go-ci-complete.yml@main
    with:
      go-version: '1.24.6'
      linter-version: 'v1.64.8'
      ubuntu-version: '22.04'
