name: CI/CD Pipeline

on: 
  push:
    branches: ["main", "feature*"]
    tags: ['v*']
  pull_request:
    branches: ["main", "feature*"]
    
env:
  GO_VERSION: '1.23.2'
  ALPINE_VERSION: '3.20'
  PORT: '80'
  LINTER_VERS: 'v1.60.1'
  UBUNTU_VERS: '22.04'

jobs:
  ci:
    uses: github.com/Mark-Grigorev/central-ci-cd/.github/workflows/go-ci-comlete.yml@v0.0.1
    with:
      go-version: '1.23.2'
      linter-version: 'v1.60.1'
      ubuntu-version: '22.04'
